version: '2'
volumes:
  dbdata:
    external:
      name: 'ecoarbolit-dbdata'
  public:

services:
  db:
    image: 'postgres:9.5'
    env_file: .rbenv-vars
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

  smtp:
    image: 'dtheus/postfix:jessie'
    ports:
      - '25'
    env_file: .rbenv-vars
    volumes: 
      - '/etc/opendkim/keys/ecoarbolit.com:/etc/opendkim/keys/ecoarbolit.com'

  app: &app
    build: .
    depends_on:
      - db
      - smtp
    env_file: .rbenv-vars
    volumes:
      - 'public:/app/public'
      - 'uploads:/app/public/uploads'
    environment:
      VIRTUAL_HOST: ecoarbolit.com
      VIRTUAL_PORT: 3000

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/nginx/vhost.d/default:/etc/nginx/vhost.d/default
      -  public:/var/www/ecoarbolit.com/public
    depends_on:
      - app

