version: '2'
volumes:
  dbdata:
    external:
      name: 'ecoarbolit-dbdata'
  public:

networks:
  www_default:
    external:
      name: www_default
  ecoarbolit:

services:
  db:
    image: 'postgres:9.5'
    env_file: .rbenv-vars
    networks:
      - ecoarbolit
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

  smtp:
    image: 'dtheus/postfix:jessie'
    networks:
      - ecoarbolit
    ports:
      - '25'
    env_file: .rbenv-vars
    volumes: 
      - '/etc/opendkim/keys/ecoarbolit.com:/etc/opendkim/keys/ecoarbolit.com'

  app: &app
    build: .
    networks:
      - ecoarbolit
      - www_default
    depends_on:
      - db
      - smtp
    env_file: .rbenv-vars
    volumes:
      - 'public:/app/public'
    environment:
      VIRTUAL_HOST: ecoarbolit.com
      VIRTUAL_PORT: 3000

  static:
    image: nginx
    volumes:
      -  public:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - ecoarbolit
      - www_default
    environment:
      VIRTUAL_HOST: assets.ecoarbolit.com
      VIRTUAL_PORT: 80

